services:
    pix_sortable_behavior.position.orm:
        class: Pix\SortableBehaviorBundle\Services\PositionORMHandler
        public: false
        arguments:
            - "@property_accessor"
            - "@doctrine.orm.entity_manager"
        calls:
            - [ 'setPositionProperty', [%pix.sortable.behavior.position.property%] ]
            - [ 'setSortableGroups', [%pix.sortable.behavior.sortable_groups%] ]

    pix_sortable_behavior.position.mongodb:
        class: Pix\SortableBehaviorBundle\Services\PositionODMHandler
        public: false
        arguments:
            - "@property_accessor"
            - "@doctrine_mongodb.odm.document_manager"
        calls:
            - [ 'setPositionProperty', ["%pix.sortable.behavior.position.property%"] ]
            - [ 'setSortableGroups', [%pix.sortable.behavior.sortable_groups%] ]

    pix_sortable_behavior.twig.extension:
        class: Pix\SortableBehaviorBundle\Twig\ObjectPositionExtension
        arguments:
            - "@property_accessor"
            - "@pix_sortable_behavior.position"
        public: false
        tags:
            - { name: twig.extension }
