services:
    pix_sortable_behavior.position.orm:
        class: Pix\SortableBehaviorBundle\Services\PositionORMHandler
        public: false
        arguments:
            propertyAccessor: "@property_accessor"
            entityManager: "@doctrine.orm.entity_manager"
        calls:
            - [ 'setPositionProperty', [%pix.sortable.behavior.position.property%] ]

    pix_sortable_behavior.position.mongodb:
        class: Pix\SortableBehaviorBundle\Services\PositionODMHandler
        public: false
        arguments:
            propertyAccessor: "@property_accessor"
            documentManager: "@doctrine_mongodb.odm.document_manager"
        calls:
            - [ 'setPositionProperty', ["%pix.sortable.behavior.position.property%"] ]

    pix_sortable_behavior.twig.extension:
        class: Pix\SortableBehaviorBundle\Twig\ObjectPositionExtension
        arguments:
            - "@property_accessor"
            - "@pix_sortable_behavior.position"
        public: false
        tags:
            - { name: twig.extension }
